-- Remove BASIC from public sale and keep it only as legacy/internal recognition.
-- Execute after deploying backend code that removes BASIC from public catalogs.

UPDATE subscription_plan_price
SET active = FALSE, updated_at = NOW()
WHERE upper(plan_code) = 'BASIC';

-- New public prices from July 2026 commercial structure.
-- Venezuela is intentionally priced in USD.
INSERT INTO subscription_plan_price (plan_code, country_code, currency, billing_cycle, amount, active) VALUES
('FREE','PE','PEN','MONTHLY',0, TRUE),('STARTER','PE','PEN','MONTHLY',49.90, TRUE),('GROWTH','PE','PEN','MONTHLY',99.90, TRUE),('PRO','PE','PEN','MONTHLY',149.90, TRUE),('ENTERPRISE','PE','PEN','MONTHLY',299.90, TRUE),
('FREE','US','USD','MONTHLY',0, TRUE),('STARTER','US','USD','MONTHLY',14.90, TRUE),('GROWTH','US','USD','MONTHLY',29.90, TRUE),('PRO','US','USD','MONTHLY',44.90, TRUE),('ENTERPRISE','US','USD','MONTHLY',89.90, TRUE),
('FREE','VE','USD','MONTHLY',0, TRUE),('STARTER','VE','USD','MONTHLY',14.90, TRUE),('GROWTH','VE','USD','MONTHLY',29.90, TRUE),('PRO','VE','USD','MONTHLY',44.90, TRUE),('ENTERPRISE','VE','USD','MONTHLY',89.90, TRUE),
('FREE','CO','COP','MONTHLY',0, TRUE),('STARTER','CO','COP','MONTHLY',59900, TRUE),('GROWTH','CO','COP','MONTHLY',119900, TRUE),('PRO','CO','COP','MONTHLY',179900, TRUE),('ENTERPRISE','CO','COP','MONTHLY',359900, TRUE),
('FREE','MX','MXN','MONTHLY',0, TRUE),('STARTER','MX','MXN','MONTHLY',299, TRUE),('GROWTH','MX','MXN','MONTHLY',599, TRUE),('PRO','MX','MXN','MONTHLY',899, TRUE),('ENTERPRISE','MX','MXN','MONTHLY',1799, TRUE),
('FREE','CL','CLP','MONTHLY',0, TRUE),('STARTER','CL','CLP','MONTHLY',13900, TRUE),('GROWTH','CL','CLP','MONTHLY',27900, TRUE),('PRO','CL','CLP','MONTHLY',41900, TRUE),('ENTERPRISE','CL','CLP','MONTHLY',83900, TRUE),
('FREE','AR','ARS','MONTHLY',0, TRUE),('STARTER','AR','ARS','MONTHLY',19900, TRUE),('GROWTH','AR','ARS','MONTHLY',39900, TRUE),('PRO','AR','ARS','MONTHLY',59900, TRUE),('ENTERPRISE','AR','ARS','MONTHLY',119900, TRUE),
('FREE','BO','USD','MONTHLY',0, TRUE),('STARTER','BO','USD','MONTHLY',14.90, TRUE),('GROWTH','BO','USD','MONTHLY',29.90, TRUE),('PRO','BO','USD','MONTHLY',44.90, TRUE),('ENTERPRISE','BO','USD','MONTHLY',89.90, TRUE),
('FREE','BR','BRL','MONTHLY',0, TRUE),('STARTER','BR','BRL','MONTHLY',79, TRUE),('GROWTH','BR','BRL','MONTHLY',159, TRUE),('PRO','BR','BRL','MONTHLY',239, TRUE),('ENTERPRISE','BR','BRL','MONTHLY',479, TRUE),
('FREE','EU','EUR','MONTHLY',0, TRUE),('STARTER','EU','EUR','MONTHLY',13.90, TRUE),('GROWTH','EU','EUR','MONTHLY',27.90, TRUE),('PRO','EU','EUR','MONTHLY',41.90, TRUE),('ENTERPRISE','EU','EUR','MONTHLY',83.90, TRUE),
('FREE','UY','USD','MONTHLY',0, TRUE),('STARTER','UY','USD','MONTHLY',14.90, TRUE),('GROWTH','UY','USD','MONTHLY',29.90, TRUE),('PRO','UY','USD','MONTHLY',44.90, TRUE),('ENTERPRISE','UY','USD','MONTHLY',89.90, TRUE),
('FREE','PY','USD','MONTHLY',0, TRUE),('STARTER','PY','USD','MONTHLY',14.90, TRUE),('GROWTH','PY','USD','MONTHLY',29.90, TRUE),('PRO','PY','USD','MONTHLY',44.90, TRUE),('ENTERPRISE','PY','USD','MONTHLY',89.90, TRUE),
('FREE','CR','USD','MONTHLY',0, TRUE),('STARTER','CR','USD','MONTHLY',14.90, TRUE),('GROWTH','CR','USD','MONTHLY',29.90, TRUE),('PRO','CR','USD','MONTHLY',44.90, TRUE),('ENTERPRISE','CR','USD','MONTHLY',89.90, TRUE),
('FREE','DO','USD','MONTHLY',0, TRUE),('STARTER','DO','USD','MONTHLY',14.90, TRUE),('GROWTH','DO','USD','MONTHLY',29.90, TRUE),('PRO','DO','USD','MONTHLY',44.90, TRUE),('ENTERPRISE','DO','USD','MONTHLY',89.90, TRUE),
('FREE','GT','USD','MONTHLY',0, TRUE),('STARTER','GT','USD','MONTHLY',14.90, TRUE),('GROWTH','GT','USD','MONTHLY',29.90, TRUE),('PRO','GT','USD','MONTHLY',44.90, TRUE),('ENTERPRISE','GT','USD','MONTHLY',89.90, TRUE)
ON CONFLICT (plan_code, country_code, billing_cycle) DO UPDATE SET
    currency = EXCLUDED.currency,
    amount = EXCLUDED.amount,
    active = EXCLUDED.active,
    updated_at = NOW();
