CREATE TABLE IF NOT EXISTS subscription_plan_price (
    id BIGSERIAL PRIMARY KEY,
    plan_code VARCHAR(40) NOT NULL,
    country_code VARCHAR(8) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    billing_cycle VARCHAR(20) NOT NULL DEFAULT 'MONTHLY',
    amount NUMERIC(12,2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_subscription_plan_price UNIQUE (plan_code, country_code, billing_cycle)
);

INSERT INTO subscription_plan_price (plan_code, country_code, currency, billing_cycle, amount) VALUES
('FREE','PE','PEN','MONTHLY',0),('STARTER','PE','PEN','MONTHLY',49.90),('GROWTH','PE','PEN','MONTHLY',99.90),('PRO','PE','PEN','MONTHLY',149.90),('ENTERPRISE','PE','PEN','MONTHLY',299.90),
('FREE','US','USD','MONTHLY',0),('STARTER','US','USD','MONTHLY',14.90),('GROWTH','US','USD','MONTHLY',29.90),('PRO','US','USD','MONTHLY',44.90),('ENTERPRISE','US','USD','MONTHLY',89.90),
('FREE','VE','USD','MONTHLY',0),('STARTER','VE','USD','MONTHLY',14.90),('GROWTH','VE','USD','MONTHLY',29.90),('PRO','VE','USD','MONTHLY',44.90),('ENTERPRISE','VE','USD','MONTHLY',89.90),
('FREE','CO','COP','MONTHLY',0),('STARTER','CO','COP','MONTHLY',59900),('GROWTH','CO','COP','MONTHLY',119900),('PRO','CO','COP','MONTHLY',179900),('ENTERPRISE','CO','COP','MONTHLY',359900),
('FREE','MX','MXN','MONTHLY',0),('STARTER','MX','MXN','MONTHLY',299),('GROWTH','MX','MXN','MONTHLY',599),('PRO','MX','MXN','MONTHLY',899),('ENTERPRISE','MX','MXN','MONTHLY',1799),
('FREE','CL','CLP','MONTHLY',0),('STARTER','CL','CLP','MONTHLY',13900),('GROWTH','CL','CLP','MONTHLY',27900),('PRO','CL','CLP','MONTHLY',41900),('ENTERPRISE','CL','CLP','MONTHLY',83900),
('FREE','AR','ARS','MONTHLY',0),('STARTER','AR','ARS','MONTHLY',19900),('GROWTH','AR','ARS','MONTHLY',39900),('PRO','AR','ARS','MONTHLY',59900),('ENTERPRISE','AR','ARS','MONTHLY',119900),
('FREE','BO','USD','MONTHLY',0),('STARTER','BO','USD','MONTHLY',14.90),('GROWTH','BO','USD','MONTHLY',29.90),('PRO','BO','USD','MONTHLY',44.90),('ENTERPRISE','BO','USD','MONTHLY',89.90),
('FREE','BR','BRL','MONTHLY',0),('STARTER','BR','BRL','MONTHLY',79),('GROWTH','BR','BRL','MONTHLY',159),('PRO','BR','BRL','MONTHLY',239),('ENTERPRISE','BR','BRL','MONTHLY',479),
('FREE','EU','EUR','MONTHLY',0),('STARTER','EU','EUR','MONTHLY',13.90),('GROWTH','EU','EUR','MONTHLY',27.90),('PRO','EU','EUR','MONTHLY',41.90),('ENTERPRISE','EU','EUR','MONTHLY',83.90),
('FREE','UY','USD','MONTHLY',0),('STARTER','UY','USD','MONTHLY',14.90),('GROWTH','UY','USD','MONTHLY',29.90),('PRO','UY','USD','MONTHLY',44.90),('ENTERPRISE','UY','USD','MONTHLY',89.90),
('FREE','PY','USD','MONTHLY',0),('STARTER','PY','USD','MONTHLY',14.90),('GROWTH','PY','USD','MONTHLY',29.90),('PRO','PY','USD','MONTHLY',44.90),('ENTERPRISE','PY','USD','MONTHLY',89.90),
('FREE','CR','USD','MONTHLY',0),('STARTER','CR','USD','MONTHLY',14.90),('GROWTH','CR','USD','MONTHLY',29.90),('PRO','CR','USD','MONTHLY',44.90),('ENTERPRISE','CR','USD','MONTHLY',89.90),
('FREE','DO','USD','MONTHLY',0),('STARTER','DO','USD','MONTHLY',14.90),('GROWTH','DO','USD','MONTHLY',29.90),('PRO','DO','USD','MONTHLY',44.90),('ENTERPRISE','DO','USD','MONTHLY',89.90),
('FREE','GT','USD','MONTHLY',0),('STARTER','GT','USD','MONTHLY',14.90),('GROWTH','GT','USD','MONTHLY',29.90),('PRO','GT','USD','MONTHLY',44.90),('ENTERPRISE','GT','USD','MONTHLY',89.90)
ON CONFLICT (plan_code, country_code, billing_cycle) DO UPDATE SET
    currency = EXCLUDED.currency,
    amount = EXCLUDED.amount,
    active = TRUE,
    updated_at = NOW();
