CREATE TABLE IF NOT EXISTS subscription_plan_price (
    id BIGSERIAL PRIMARY KEY,
    plan_code VARCHAR(40) NOT NULL,
    country_code VARCHAR(8) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    billing_cycle VARCHAR(20) NOT NULL DEFAULT 'MONTHLY',
    amount NUMERIC(12,2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_subscription_plan_price UNIQUE (plan_code, country_code, billing_cycle)
);

INSERT INTO subscription_plan_price (plan_code, country_code, currency, billing_cycle, amount) VALUES
('FREE','PE','PEN','MONTHLY',0),('BASIC','PE','PEN','MONTHLY',39.90),('STARTER','PE','PEN','MONTHLY',79.90),('GROWTH','PE','PEN','MONTHLY',139.90),('PRO','PE','PEN','MONTHLY',229.90),('ENTERPRISE','PE','PEN','MONTHLY',399.90),
('FREE','US','USD','MONTHLY',0),('BASIC','US','USD','MONTHLY',12),('STARTER','US','USD','MONTHLY',24),('GROWTH','US','USD','MONTHLY',41),('PRO','US','USD','MONTHLY',68),('ENTERPRISE','US','USD','MONTHLY',118),
('FREE','CO','COP','MONTHLY',0),('BASIC','CO','COP','MONTHLY',39900),('STARTER','CO','COP','MONTHLY',79900),('GROWTH','CO','COP','MONTHLY',139900),('PRO','CO','COP','MONTHLY',229900),('ENTERPRISE','CO','COP','MONTHLY',399900),
('FREE','MX','MXN','MONTHLY',0),('BASIC','MX','MXN','MONTHLY',199),('STARTER','MX','MXN','MONTHLY',399),('GROWTH','MX','MXN','MONTHLY',699),('PRO','MX','MXN','MONTHLY',1149),('ENTERPRISE','MX','MXN','MONTHLY',1999),
('FREE','CL','CLP','MONTHLY',0),('BASIC','CL','CLP','MONTHLY',10900),('STARTER','CL','CLP','MONTHLY',21900),('GROWTH','CL','CLP','MONTHLY',38900),('PRO','CL','CLP','MONTHLY',63900),('ENTERPRISE','CL','CLP','MONTHLY',111900),
('FREE','AR','ARS','MONTHLY',0),('BASIC','AR','ARS','MONTHLY',11900),('STARTER','AR','ARS','MONTHLY',23900),('GROWTH','AR','ARS','MONTHLY',41900),('PRO','AR','ARS','MONTHLY',68900),('ENTERPRISE','AR','ARS','MONTHLY',119900),
('FREE','BO','USD','MONTHLY',0),('BASIC','BO','USD','MONTHLY',12),('STARTER','BO','USD','MONTHLY',24),('GROWTH','BO','USD','MONTHLY',41),('PRO','BO','USD','MONTHLY',68),('ENTERPRISE','BO','USD','MONTHLY',118),
('FREE','BR','BRL','MONTHLY',0),('BASIC','BR','BRL','MONTHLY',59),('STARTER','BR','BRL','MONTHLY',119),('GROWTH','BR','BRL','MONTHLY',209),('PRO','BR','BRL','MONTHLY',339),('ENTERPRISE','BR','BRL','MONTHLY',599),
('FREE','EU','EUR','MONTHLY',0),('BASIC','EU','EUR','MONTHLY',11),('STARTER','EU','EUR','MONTHLY',22),('GROWTH','EU','EUR','MONTHLY',37),('PRO','EU','EUR','MONTHLY',61),('ENTERPRISE','EU','EUR','MONTHLY',107),
('FREE','UY','USD','MONTHLY',0),('BASIC','UY','USD','MONTHLY',12),('STARTER','UY','USD','MONTHLY',24),('GROWTH','UY','USD','MONTHLY',41),('PRO','UY','USD','MONTHLY',68),('ENTERPRISE','UY','USD','MONTHLY',118),
('FREE','PY','USD','MONTHLY',0),('BASIC','PY','USD','MONTHLY',12),('STARTER','PY','USD','MONTHLY',24),('GROWTH','PY','USD','MONTHLY',41),('PRO','PY','USD','MONTHLY',68),('ENTERPRISE','PY','USD','MONTHLY',118),
('FREE','CR','USD','MONTHLY',0),('BASIC','CR','USD','MONTHLY',12),('STARTER','CR','USD','MONTHLY',24),('GROWTH','CR','USD','MONTHLY',41),('PRO','CR','USD','MONTHLY',68),('ENTERPRISE','CR','USD','MONTHLY',118),
('FREE','DO','USD','MONTHLY',0),('BASIC','DO','USD','MONTHLY',12),('STARTER','DO','USD','MONTHLY',24),('GROWTH','DO','USD','MONTHLY',41),('PRO','DO','USD','MONTHLY',68),('ENTERPRISE','DO','USD','MONTHLY',118),
('FREE','GT','USD','MONTHLY',0),('BASIC','GT','USD','MONTHLY',12),('STARTER','GT','USD','MONTHLY',24),('GROWTH','GT','USD','MONTHLY',41),('PRO','GT','USD','MONTHLY',68),('ENTERPRISE','GT','USD','MONTHLY',118)
ON CONFLICT (plan_code, country_code, billing_cycle) DO UPDATE SET
    currency = EXCLUDED.currency,
    amount = EXCLUDED.amount,
    active = TRUE,
    updated_at = NOW();
