spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false   # 👈 importante en prod
    properties:
      hibernate.format_sql: false
      hibernate.jdbc.time_zone: UTC
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: ERROR

server:
  port: ${PORT:8080}

runpod:
  enabled: ${RUNPOD_ENABLED:true}


feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 600000


firebase:
  enabled: true