package com.gods.saas.domain.enums;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_REMINDER_60,
    BOOKING_REMINDER_30,
    POINTS_EARNED,
    PROMOTION_CREATED,
    REWARD_CREATED,
    REWARD_REDEEMED,
    BARBER_PAYMENT_CREATED,
    CAMPAIGN_INACTIVE_15,
    CAMPAIGN_INACTIVE_30
}