package com.gods.saas.service.impl;
import com.gods.saas.domain.dto.response.ShowcasePageResponse;
import com.gods.saas.domain.dto.response.ShowcaseResponse;
import com.gods.saas.domain.enums.ShowcaseStatus;
import com.gods.saas.domain.model.*;
import com.gods.saas.domain.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;
import org.springframework.web.multipart.MultipartFile;
import java.time.LocalDateTime;
import java.util.*;
@Service @RequiredArgsConstructor
public class ProfessionalShowcaseService {
 private static final int MAX_FEATURED = 8;
 private final ProfessionalShowcaseRepository repository; private final TenantRepository tenantRepository; private final BranchRepository branchRepository; private final AppUserRepository appUserRepository; private final ServiceRepository serviceRepository; private final UserTenantRoleRepository roleRepository; private final SubscriptionRepository subscriptionRepository; private final CloudinaryStorageService storage;
 @Transactional(readOnly=true) public List<ShowcaseResponse> mine(Long tenantId,Long userId){return repository.findByTenant_IdAndProfessional_IdOrderByCreatedAtDesc(tenantId,userId).stream().map(ShowcaseResponse::from).toList();}
 @Transactional public ShowcaseResponse create(Long tenantId,Long userId,Long branchId,Long serviceId,String title,String description,String mediaType,Integer durationSeconds,boolean consent,MultipartFile file){
  if(!consent)throw new IllegalArgumentException("Debes confirmar la autorizacion de uso de imagen."); String clean=title==null?"":title.trim();if(clean.isEmpty()||clean.length()>120)throw new IllegalArgumentException("Escribe un titulo de hasta 120 caracteres.");
  Tenant tenant=tenantRepository.findById(tenantId).orElseThrow(()->new IllegalArgumentException("Negocio no encontrado.")); Branch branch=branchRepository.findByIdAndTenant_Id(branchId,tenantId).orElseThrow(()->new IllegalArgumentException("Sede no encontrada.")); AppUser user=appUserRepository.findByIdAndTenant_Id(userId,tenantId).orElseThrow(()->new IllegalArgumentException("Profesional no encontrado."));
  if(!roleRepository.existsByUser_IdAndTenant_IdAndBranch_IdAndRole(userId,tenantId,branchId,RoleType.BARBER))throw new IllegalStateException("No tienes perfil profesional activo en esta sede.");
  ServiceEntity service=serviceId==null?null:serviceRepository.findByIdAndTenant_IdAndDeletedAtIsNull(serviceId,tenantId).orElseThrow(()->new IllegalArgumentException("Servicio no encontrado."));
  String type=mediaType==null?"IMAGE":mediaType.trim().toUpperCase();
  if(!List.of("IMAGE","VIDEO").contains(type))throw new IllegalArgumentException("Tipo de medio invalido.");
  String plan=subscriptionRepository.findTopByTenantIdOrderByFechaInicioDesc(tenantId).map(Subscription::getPlan).map(SubscriptionPlanCatalog::publicPlan).orElseGet(()->{try{return SubscriptionPlanCatalog.publicPlan(tenant.getPlan());}catch(RuntimeException ignored){return SubscriptionPlanCatalog.FREE;}});
  int totalLimit=switch(plan){case "BASIC"->25;case "STARTER"->50;case "GROWTH"->100;case "PRO"->200;case "ENTERPRISE"->500;default->10;};
  int videoLimit=switch(plan){case "BASIC"->5;case "STARTER"->10;case "GROWTH"->25;case "PRO"->50;case "ENTERPRISE"->150;default->0;};
  long current=repository.countByTenant_IdAndProfessional_IdAndStatusNot(tenantId,userId,ShowcaseStatus.ARCHIVED);
  if(current>=totalLimit)throw new IllegalStateException("Alcanzaste el limite de "+totalLimit+" trabajos activos de tu plan.");
  if("VIDEO".equals(type)){long videos=repository.countByTenant_IdAndProfessional_IdAndMediaTypeAndStatusNot(tenantId,userId,"VIDEO",ShowcaseStatus.ARCHIVED);if(videos>=videoLimit)throw new IllegalStateException(videoLimit==0?"Tu plan no incluye videos en la vitrina.":"Alcanzaste el limite de videos de tu plan.");}
  if("VIDEO".equals(type)&&(durationSeconds==null||durationSeconds<1||durationSeconds>90))throw new IllegalArgumentException("El video debe durar entre 1 y 90 segundos.");
  var upload="VIDEO".equals(type)?storage.uploadShowcaseVideo(tenantId,userId,file):storage.uploadShowcaseImage(tenantId,userId,file);
  String thumbnail="VIDEO".equals(type)?storage.videoThumbnailUrl(upload.getSecureUrl()):upload.getSecureUrl();
  ProfessionalShowcase item=ProfessionalShowcase.builder().tenant(tenant).branch(branch).professional(user).createdBy(user).service(service).originType("PROFESSIONAL_WORK").visibilityScope("ORIGIN_BRANCH").title(clean).description(description==null?null:description.trim()).mediaType(type).imageUrl(upload.getSecureUrl()).thumbnailUrl(thumbnail).imagePublicId(upload.getPublicId()).durationSeconds("VIDEO".equals(type)?durationSeconds:null).status(ShowcaseStatus.PENDING_APPROVAL).clientImageConsent(true).build(); return ShowcaseResponse.from(repository.save(item));
 }
 @Transactional public ShowcaseResponse createOwnerCatalog(Long tenantId,Long actorId,Long branchId,List<Long> branchIds,Long serviceId,String title,String description,String category,String collectionName,String scheduledAt,String visibilityScope,String mediaType,Integer durationSeconds,boolean consent,MultipartFile file){
  if(!consent)throw new IllegalArgumentException("Debes confirmar la autorizacion para publicar este contenido.");
  String clean=title==null?"":title.trim();if(clean.isEmpty()||clean.length()>120)throw new IllegalArgumentException("Escribe un titulo de hasta 120 caracteres.");
  if(file==null||file.isEmpty())throw new IllegalArgumentException("Selecciona una foto o video.");
  Tenant tenant=tenantRepository.findById(tenantId).orElseThrow(()->new IllegalArgumentException("Negocio no encontrado."));
  AppUser actor=appUserRepository.findByIdAndTenant_Id(actorId,tenantId).orElseThrow(()->new IllegalArgumentException("Usuario no encontrado."));
  String scope=visibilityScope==null?"ALL_BRANCHES":visibilityScope.trim().toUpperCase();if(!List.of("ALL_BRANCHES","SELECTED_BRANCHES","ORIGIN_BRANCH").contains(scope))throw new IllegalArgumentException("Alcance de sedes invalido.");
  Branch origin=null;Set<Branch> selected=new LinkedHashSet<>();
  if("ORIGIN_BRANCH".equals(scope)){if(branchId==null)throw new IllegalArgumentException("Selecciona la sede.");origin=branchRepository.findByIdAndTenant_Id(branchId,tenantId).orElseThrow(()->new IllegalArgumentException("Sede no encontrada."));}
  if("SELECTED_BRANCHES".equals(scope)){if(branchIds==null||branchIds.isEmpty())throw new IllegalArgumentException("Selecciona al menos una sede.");for(Long id:new LinkedHashSet<>(branchIds))selected.add(branchRepository.findByIdAndTenant_Id(id,tenantId).orElseThrow(()->new IllegalArgumentException("Una sede seleccionada no pertenece al negocio.")));}
  ServiceEntity service=serviceId==null?null:serviceRepository.findByIdAndTenant_IdAndDeletedAtIsNull(serviceId,tenantId).orElseThrow(()->new IllegalArgumentException("Servicio no encontrado."));
  String type=mediaType==null?"IMAGE":mediaType.trim().toUpperCase();if(!List.of("IMAGE","VIDEO").contains(type))throw new IllegalArgumentException("Tipo de medio invalido.");if("VIDEO".equals(type)&&(durationSeconds==null||durationSeconds<1||durationSeconds>90))throw new IllegalArgumentException("El video debe durar entre 1 y 90 segundos.");
  var upload="VIDEO".equals(type)?storage.uploadShowcaseVideo(tenantId,actorId,file):storage.uploadShowcaseImage(tenantId,actorId,file);String thumbnail="VIDEO".equals(type)?storage.videoThumbnailUrl(upload.getSecureUrl()):upload.getSecureUrl();
  String cleanCollection=collectionName==null?null:collectionName.trim();if(cleanCollection!=null&&cleanCollection.isEmpty())cleanCollection=null;if(cleanCollection!=null&&cleanCollection.length()>80)throw new IllegalArgumentException("La coleccion puede tener hasta 80 caracteres.");
  LocalDateTime publicationTime=LocalDateTime.now();if(scheduledAt!=null&&!scheduledAt.isBlank()){try{publicationTime=LocalDateTime.parse(scheduledAt.trim());}catch(RuntimeException ex){throw new IllegalArgumentException("Fecha de publicacion invalida.");}if(!publicationTime.isAfter(LocalDateTime.now().plusMinutes(4)))throw new IllegalArgumentException("Programa la publicacion al menos 5 minutos despues.");}
  ProfessionalShowcase item=ProfessionalShowcase.builder().tenant(tenant).branch(origin).professional(null).createdBy(actor).selectedBranches(selected).service(service).originType("TENANT_CATALOG").visibilityScope(scope).category(category==null?null:category.trim()).collectionName(cleanCollection).title(clean).description(description==null?null:description.trim()).mediaType(type).imageUrl(upload.getSecureUrl()).thumbnailUrl(thumbnail).imagePublicId(upload.getPublicId()).durationSeconds("VIDEO".equals(type)?durationSeconds:null).status(ShowcaseStatus.PUBLISHED).clientImageConsent(true).publishedAt(publicationTime).moderatedBy(actor).moderatedAt(LocalDateTime.now()).build();return ShowcaseResponse.from(repository.save(item));
 }
 @Transactional public ShowcaseResponse reviseRejectedMine(Long tenantId,Long userId,Long id,String title,String description){
  ProfessionalShowcase x=owned(tenantId,userId,id);
  if(x.getStatus()!=ShowcaseStatus.REJECTED)throw new IllegalStateException("Solo puedes corregir trabajos rechazados.");
  String clean=title==null?"":title.trim();
  if(clean.isEmpty()||clean.length()>120)throw new IllegalArgumentException("Escribe un titulo de hasta 120 caracteres.");
  String detail=description==null?null:description.trim();
  if(detail!=null&&detail.length()>600)throw new IllegalArgumentException("La descripcion puede tener hasta 600 caracteres.");
  x.setTitle(clean);x.setDescription(detail==null||detail.isEmpty()?null:detail);x.setStatus(ShowcaseStatus.PENDING_APPROVAL);x.setRejectionReason(null);x.setModeratedAt(null);x.setModeratedBy(null);x.setPublishedAt(null);x.setArchivedAt(null);
  return ShowcaseResponse.from(repository.save(x));
 }
 @Transactional public ShowcaseResponse reviseRejectedMineWithMedia(Long tenantId,Long userId,Long id,String title,String description,String mediaType,Integer durationSeconds,MultipartFile file){
  ProfessionalShowcase x=owned(tenantId,userId,id);
  if(x.getStatus()!=ShowcaseStatus.REJECTED)throw new IllegalStateException("Solo puedes corregir trabajos rechazados.");
  if(file==null||file.isEmpty())throw new IllegalArgumentException("Selecciona la nueva foto o video.");
  String clean=title==null?"":title.trim();if(clean.isEmpty()||clean.length()>120)throw new IllegalArgumentException("Escribe un titulo de hasta 120 caracteres.");
  String detail=description==null?null:description.trim();if(detail!=null&&detail.length()>600)throw new IllegalArgumentException("La descripcion puede tener hasta 600 caracteres.");
  String type=mediaType==null?"IMAGE":mediaType.trim().toUpperCase();if(!List.of("IMAGE","VIDEO").contains(type))throw new IllegalArgumentException("Tipo de medio invalido.");
  if("VIDEO".equals(type)&&(durationSeconds==null||durationSeconds<1||durationSeconds>90))throw new IllegalArgumentException("El video debe durar entre 1 y 90 segundos.");
  var upload="VIDEO".equals(type)?storage.uploadShowcaseVideo(tenantId,userId,file):storage.uploadShowcaseImage(tenantId,userId,file);
  String oldPublicId=x.getImagePublicId();String oldMediaType=x.getMediaType();
  x.setTitle(clean);x.setDescription(detail==null||detail.isEmpty()?null:detail);x.setMediaType(type);x.setImageUrl(upload.getSecureUrl());x.setThumbnailUrl("VIDEO".equals(type)?storage.videoThumbnailUrl(upload.getSecureUrl()):upload.getSecureUrl());x.setImagePublicId(upload.getPublicId());x.setDurationSeconds("VIDEO".equals(type)?durationSeconds:null);x.setStatus(ShowcaseStatus.PENDING_APPROVAL);x.setRejectionReason(null);x.setModeratedAt(null);x.setModeratedBy(null);x.setPublishedAt(null);x.setArchivedAt(null);
  ShowcaseResponse response=ShowcaseResponse.from(repository.save(x));
  TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){@Override public void afterCommit(){try{storage.deleteShowcaseMedia(oldPublicId,oldMediaType);}catch(RuntimeException ignored){}}});
  return response;
 } @Transactional public ShowcaseResponse restoreMine(Long tenantId,Long userId,Long id){ProfessionalShowcase x=owned(tenantId,userId,id);if(x.getStatus()!=ShowcaseStatus.ARCHIVED)throw new IllegalStateException("Solo puedes restaurar trabajos archivados.");x.setStatus(ShowcaseStatus.PENDING_APPROVAL);x.setArchivedAt(null);x.setPublishedAt(null);x.setModeratedAt(null);x.setModeratedBy(null);x.setRejectionReason(null);return ShowcaseResponse.from(repository.save(x));}
 @Transactional public void deleteMine(Long tenantId,Long userId,Long id){ProfessionalShowcase x=owned(tenantId,userId,id);if(x.getStatus()!=ShowcaseStatus.ARCHIVED)throw new IllegalStateException("Archiva el trabajo antes de eliminarlo.");storage.deleteShowcaseMedia(x.getImagePublicId(),x.getMediaType());repository.delete(x);}
 @Transactional public ShowcaseResponse setFeatured(Long tenantId,Long actorId,Long id,boolean featured){ProfessionalShowcase x=tenantItem(tenantId,id);if(x.getStatus()!=ShowcaseStatus.PUBLISHED)throw new IllegalStateException("Solo puedes destacar publicaciones activas.");if(featured&&!x.isFeatured()){long total=repository.countByTenant_IdAndStatusAndFeaturedTrue(tenantId,ShowcaseStatus.PUBLISHED);if(total>=MAX_FEATURED)throw new IllegalStateException("Puedes destacar hasta "+MAX_FEATURED+" publicaciones. Quita una para continuar.");List<ProfessionalShowcase> ordered=featuredItems(tenantId);x.setSortOrder(ordered.size()+1);}if(!featured){x.setSortOrder(0);}x.setFeatured(featured);return ShowcaseResponse.from(repository.save(x));}
 @Transactional public ShowcaseResponse moveFeatured(Long tenantId,Long actorId,Long id,String direction){ProfessionalShowcase x=tenantItem(tenantId,id);if(x.getStatus()!=ShowcaseStatus.PUBLISHED||!x.isFeatured())throw new IllegalStateException("La publicación debe estar destacada para cambiar su prioridad.");if(!"UP".equalsIgnoreCase(direction)&&!"DOWN".equalsIgnoreCase(direction))throw new IllegalArgumentException("Dirección de prioridad inválida.");List<ProfessionalShowcase> ordered=featuredItems(tenantId);for(int i=0;i<ordered.size();i++)ordered.get(i).setSortOrder(i+1);int index=ordered.indexOf(x);int target="UP".equalsIgnoreCase(direction)?index-1:"DOWN".equalsIgnoreCase(direction)?index+1:-1;if(target<0||target>=ordered.size()){repository.saveAll(ordered);return ShowcaseResponse.from(x);}ProfessionalShowcase other=ordered.get(target);int currentOrder=x.getSortOrder();x.setSortOrder(other.getSortOrder());other.setSortOrder(currentOrder);repository.saveAll(ordered);return ShowcaseResponse.from(x);}
 private List<ProfessionalShowcase> featuredItems(Long tenantId){return new ArrayList<>(repository.findByTenant_IdAndStatusAndFeaturedTrueOrderBySortOrderAscPublishedAtDesc(tenantId,ShowcaseStatus.PUBLISHED));}
 private ProfessionalShowcase owned(Long tenantId,Long userId,Long id){ProfessionalShowcase x=repository.findByIdAndTenant_Id(id,tenantId).orElseThrow(()->new IllegalArgumentException("Trabajo no encontrado."));if(x.getProfessional()==null||!x.getProfessional().getId().equals(userId))throw new IllegalStateException("No puedes modificar este trabajo.");return x;} @Transactional public ShowcaseResponse archiveMine(Long tenantId,Long userId,Long id){ProfessionalShowcase x=owned(tenantId,userId,id);x.setStatus(ShowcaseStatus.ARCHIVED);x.setFeatured(false);x.setSortOrder(0);x.setArchivedAt(LocalDateTime.now());return ShowcaseResponse.from(repository.save(x));}
 @Transactional(readOnly=true) public List<ShowcaseResponse> ownerList(Long tenantId,String status){ShowcaseStatus parsed=status==null||status.isBlank()?null:ShowcaseStatus.valueOf(status.trim().toUpperCase());List<ProfessionalShowcase> data=parsed==null?repository.findByTenant_IdOrderByCreatedAtDesc(tenantId):parsed==ShowcaseStatus.PUBLISHED?repository.findByTenant_IdAndStatusOrderByFeaturedDescSortOrderAscCreatedAtDesc(tenantId,parsed):repository.findByTenant_IdAndStatusOrderByCreatedAtDesc(tenantId,parsed);return data.stream().map(ShowcaseResponse::from).toList();}
 @Transactional public ShowcaseResponse moderate(Long tenantId,Long actorId,Long id,String status,String reason){ShowcaseStatus target=ShowcaseStatus.valueOf(status.trim().toUpperCase());if(target!=ShowcaseStatus.PUBLISHED&&target!=ShowcaseStatus.REJECTED)throw new IllegalArgumentException("Estado de moderacion invalido.");ProfessionalShowcase x=repository.findByIdAndTenant_Id(id,tenantId).orElseThrow(()->new IllegalArgumentException("Trabajo no encontrado."));AppUser actor=appUserRepository.findByIdAndTenant_Id(actorId,tenantId).orElseThrow();x.setStatus(target);x.setModeratedBy(actor);x.setModeratedAt(LocalDateTime.now());x.setRejectionReason(target==ShowcaseStatus.REJECTED?(reason==null?"No aprobado":reason.trim()):null);if(target==ShowcaseStatus.REJECTED){x.setFeatured(false);x.setSortOrder(0);}x.setPublishedAt(target==ShowcaseStatus.PUBLISHED?LocalDateTime.now():null);return ShowcaseResponse.from(repository.save(x));}
 @Transactional public ShowcaseResponse archiveByOwner(Long tenantId,Long actorId,Long id){ProfessionalShowcase x=tenantItem(tenantId,id);AppUser actor=appUserRepository.findByIdAndTenant_Id(actorId,tenantId).orElseThrow();x.setStatus(ShowcaseStatus.ARCHIVED);x.setFeatured(false);x.setSortOrder(0);x.setArchivedAt(LocalDateTime.now());x.setModeratedBy(actor);x.setModeratedAt(LocalDateTime.now());x.setPublishedAt(null);return ShowcaseResponse.from(repository.save(x));}
 @Transactional public ShowcaseResponse publishByOwner(Long tenantId,Long actorId,Long id){ProfessionalShowcase x=tenantItem(tenantId,id);if(x.getStatus()!=ShowcaseStatus.ARCHIVED)throw new IllegalStateException("Solo puedes volver a publicar trabajos pausados.");AppUser actor=appUserRepository.findByIdAndTenant_Id(actorId,tenantId).orElseThrow();x.setStatus(ShowcaseStatus.PUBLISHED);x.setArchivedAt(null);x.setPublishedAt(LocalDateTime.now());x.setModeratedBy(actor);x.setModeratedAt(LocalDateTime.now());x.setRejectionReason(null);return ShowcaseResponse.from(repository.save(x));}
 @Transactional public void deleteByOwner(Long tenantId,Long id){ProfessionalShowcase x=tenantItem(tenantId,id);if(x.getStatus()!=ShowcaseStatus.ARCHIVED)throw new IllegalStateException("Pausa el trabajo antes de eliminarlo.");storage.deleteShowcaseMedia(x.getImagePublicId(),x.getMediaType());repository.delete(x);}
 private ProfessionalShowcase tenantItem(Long tenantId,Long id){return repository.findByIdAndTenant_Id(id,tenantId).orElseThrow(()->new IllegalArgumentException("Trabajo no encontrado."));} @Transactional(readOnly=true) public ShowcaseResponse publicDetail(Long id){ProfessionalShowcase x=repository.findById(id).orElseThrow(()->new IllegalArgumentException("Publicacion no encontrada."));if(x.getStatus()!=ShowcaseStatus.PUBLISHED||x.getPublishedAt()==null||x.getPublishedAt().isAfter(LocalDateTime.now()))throw new IllegalArgumentException("Publicacion no disponible.");return ShowcaseResponse.from(x);}
 @Transactional(readOnly=true) public List<ShowcaseResponse> published(Long tenantId,Long branchId,Long professionalId){return repository.findPublishedForBranch(tenantId,branchId,professionalId,ShowcaseStatus.PUBLISHED).stream().limit(60).map(ShowcaseResponse::from).toList();}
 @Transactional(readOnly=true) public ShowcasePageResponse publishedPage(Long tenantId,Collection<Long> branchIds,Long professionalId,int page,int size){if(branchIds==null||branchIds.isEmpty())throw new IllegalArgumentException("Selecciona al menos una sede.");List<Long> clean=branchIds.stream().filter(Objects::nonNull).distinct().limit(25).toList();if(clean.isEmpty())throw new IllegalArgumentException("Selecciona al menos una sede.");int safePage=Math.max(0,page);int safeSize=Math.max(1,Math.min(size,24));var result=repository.findPublishedPage(tenantId,clean,professionalId,ShowcaseStatus.PUBLISHED,PageRequest.of(safePage,safeSize));return new ShowcasePageResponse(result.getContent().stream().map(ShowcaseResponse::from).toList(),safePage,safeSize,result.hasNext(),result.getTotalElements());}
}