package com.gods.saas.web.controller;
import com.gods.saas.domain.dto.response.ShowcaseResponse;import com.gods.saas.service.impl.ProfessionalShowcaseService;import lombok.RequiredArgsConstructor;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.util.List;
@RestController @RequestMapping("/api/barber/showcase") @RequiredArgsConstructor public class BarberShowcaseController {private final ProfessionalShowcaseService service;
@GetMapping public List<ShowcaseResponse> mine(@RequestAttribute("tenantId")Long tenantId,@RequestAttribute("userId")Long userId){return service.mine(tenantId,userId);}
@PostMapping(consumes="multipart/form-data") public ShowcaseResponse create(@RequestAttribute("tenantId")Long tenantId,@RequestAttribute("userId")Long userId,@RequestParam Long branchId,@RequestParam(required=false)Long serviceId,@RequestParam String title,@RequestParam(required=false)String description,@RequestParam(defaultValue="IMAGE")String mediaType,@RequestParam(required=false)Integer durationSeconds,@RequestParam boolean clientImageConsent,@RequestPart("file")MultipartFile file){return service.create(tenantId,userId,branchId,serviceId,title,description,mediaType,durationSeconds,clientImageConsent,file);}
@PutMapping(value="/{id}/revise",consumes="application/json") public ShowcaseResponse revise(@RequestAttribute("tenantId")Long tenantId,@RequestAttribute("userId")Long userId,@PathVariable Long id,@RequestBody java.util.Map<String,Object> body){return service.reviseRejectedMine(tenantId,userId,id,body.get("title")==null?null:String.valueOf(body.get("title")),body.get("description")==null?null:String.valueOf(body.get("description")));}
@PutMapping(value="/{id}/revise",consumes="multipart/form-data") public ShowcaseResponse reviseWithMedia(@RequestAttribute("tenantId")Long tenantId,@RequestAttribute("userId")Long userId,@PathVariable Long id,@RequestParam String title,@RequestParam(required=false)String description,@RequestParam(defaultValue="IMAGE")String mediaType,@RequestParam(required=false)Integer durationSeconds,@RequestPart("file")MultipartFile file){return service.reviseRejectedMineWithMedia(tenantId,userId,id,title,description,mediaType,durationSeconds,file);}
@PostMapping("/{id}/archive") public ShowcaseResponse archive(@RequestAttribute("tenantId")Long tenantId,@RequestAttribute("userId")Long userId,@PathVariable Long id){return service.archiveMine(tenantId,userId,id);}
@PostMapping("/{id}/restore") public ShowcaseResponse restore(@RequestAttribute("tenantId")Long tenantId,@RequestAttribute("userId")Long userId,@PathVariable Long id){return service.restoreMine(tenantId,userId,id);}
@DeleteMapping("/{id}") public void delete(@RequestAttribute("tenantId")Long tenantId,@RequestAttribute("userId")Long userId,@PathVariable Long id){service.deleteMine(tenantId,userId,id);}}