package com.gods.saas.web.controller;
import com.gods.saas.domain.dto.response.ShowcaseResponse;import com.gods.saas.service.impl.*;import lombok.RequiredArgsConstructor;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.util.*;
@RestController @RequestMapping("/api/owner/showcase") @RequiredArgsConstructor public class OwnerShowcaseController {private final ProfessionalShowcaseService service;private final AdminPermissionService permissions;
@GetMapping public List<ShowcaseResponse> list(@RequestAttribute("tenantId")Long tenantId,@RequestParam(required=false)String status){permissions.checkPermission("CONFIG_BARBERS");return service.ownerList(tenantId,status);}
@PostMapping(value="/catalog",consumes="multipart/form-data") public ShowcaseResponse createCatalog(@RequestAttribute("tenantId")Long tenantId,@RequestAttribute("userId")Long userId,@RequestParam(required=false)Long branchId,@RequestParam(required=false)List<Long> branchIds,@RequestParam(required=false)Long serviceId,@RequestParam String title,@RequestParam(required=false)String description,@RequestParam(required=false)String category,@RequestParam(defaultValue="ALL_BRANCHES")String visibilityScope,@RequestParam(defaultValue="IMAGE")String mediaType,@RequestParam(required=false)Integer durationSeconds,@RequestParam(defaultValue="false")boolean consent,@RequestPart("file")MultipartFile file){permissions.checkPermission("CONFIG_BARBERS");return service.createOwnerCatalog(tenantId,userId,branchId,branchIds,serviceId,title,description,category,visibilityScope,mediaType,durationSeconds,consent,file);}
@PostMapping("/{id}/moderate") public ShowcaseResponse moderate(@RequestAttribute("tenantId")Long tenantId,@RequestAttribute("userId")Long userId,@PathVariable Long id,@RequestBody Map<String,Object> body){permissions.checkPermission("CONFIG_BARBERS");return service.moderate(tenantId,userId,id,String.valueOf(body.get("status")),body.get("reason")==null?null:String.valueOf(body.get("reason")));}@PatchMapping("/{id}/featured") public ShowcaseResponse featured(@RequestAttribute("tenantId")Long tenantId,@RequestAttribute("userId")Long userId,@PathVariable Long id,@RequestBody Map<String,Object> body){permissions.checkPermission("CONFIG_BARBERS");return service.setFeatured(tenantId,userId,id,Boolean.TRUE.equals(body.get("featured")));}
@PostMapping("/{id}/featured/move") public ShowcaseResponse moveFeatured(@RequestAttribute("tenantId")Long tenantId,@RequestAttribute("userId")Long userId,@PathVariable Long id,@RequestBody Map<String,Object> body){permissions.checkPermission("CONFIG_BARBERS");return service.moveFeatured(tenantId,userId,id,String.valueOf(body.get("direction")));}
@PostMapping("/{id}/archive") public ShowcaseResponse archive(@RequestAttribute("tenantId")Long tenantId,@RequestAttribute("userId")Long userId,@PathVariable Long id){permissions.checkPermission("CONFIG_BARBERS");return service.archiveByOwner(tenantId,userId,id);}
@PostMapping("/{id}/publish") public ShowcaseResponse publish(@RequestAttribute("tenantId")Long tenantId,@RequestAttribute("userId")Long userId,@PathVariable Long id){permissions.checkPermission("CONFIG_BARBERS");return service.publishByOwner(tenantId,userId,id);}
@DeleteMapping("/{id}") public void delete(@RequestAttribute("tenantId")Long tenantId,@PathVariable Long id){permissions.checkPermission("CONFIG_BARBERS");service.deleteByOwner(tenantId,id);}}